// <auto-generated />
using System;
using Lunara.Infrastructure.Host.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lunara.Infrastructure.Host.Migrations;

[DbContext(typeof(LunaraDbContext))]
[Migration("20260315000000_AddModerationBlocksReports")]
partial class AddModerationBlocksReports
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "9.0.1")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("Lunara.Infrastructure.Host.Moderation.BlockEntity", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<Guid>("BlockerUserId")
                    .HasColumnType("uuid")
                    .HasColumnName("blocker_user_id");

                b.Property<Guid>("BlockedUserId")
                    .HasColumnType("uuid")
                    .HasColumnName("blocked_user_id");

                b.Property<DateTimeOffset>("CreatedAtUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("created_at_utc");

                b.HasKey("Id");

                b.HasIndex("BlockerUserId", "BlockedUserId")
                    .IsUnique()
                    .HasDatabaseName("ix_moderation_blocks_pair");

                b.ToTable("moderation_blocks");
            });

        modelBuilder.Entity("Lunara.Infrastructure.Host.Moderation.ReportEntity", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<Guid>("ReporterUserId")
                    .HasColumnType("uuid")
                    .HasColumnName("reporter_user_id");

                b.Property<Guid>("TargetUserId")
                    .HasColumnType("uuid")
                    .HasColumnName("target_user_id");

                b.Property<string>("Reason")
                    .IsRequired()
                    .HasMaxLength(500)
                    .HasColumnType("character varying(500)")
                    .HasColumnName("reason");

                b.Property<string>("Details")
                    .HasColumnType("text")
                    .HasColumnName("details");

                b.Property<DateTimeOffset>("CreatedAtUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("created_at_utc");

                b.HasKey("Id");

                b.ToTable("moderation_reports");
            });

        modelBuilder.Entity("Lunara.Infrastructure.Host.Persistence.OutboxMessageEntity", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<int>("Attempts")
                    .HasColumnType("integer");

                b.Property<string>("EventType")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)");

                b.Property<string>("LastError")
                    .HasMaxLength(2000)
                    .HasColumnType("character varying(2000)");

                b.Property<DateTimeOffset?>("LockedUntilUtc")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTimeOffset>("OccurredAtUtc")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("PayloadJson")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<int>("Status")
                    .HasColumnType("integer");

                b.HasKey("Id");

                b.HasIndex("LockedUntilUtc")
                    .HasDatabaseName("ix_outbox_locked_until");

                b.HasIndex("Status", "OccurredAtUtc")
                    .HasDatabaseName("ix_outbox_status_occurred");

                b.ToTable("OutboxMessages");
            });
#pragma warning restore 612, 618
    }
}
