// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Lunara.Infrastructure.Host.Migrations;

/// <inheritdoc />
public partial class AddInboxMessages : Migration
{
    private static readonly string[] _inboxColumns = ["Consumer", "EventId"];

    /// <inheritdoc />
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        ArgumentNullException.ThrowIfNull(migrationBuilder);

        migrationBuilder.CreateTable(
            name: "inbox_messages",
            columns: table => new
            {
                EventId = table.Column<Guid>(type: "uuid", nullable: false),
                Consumer = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                ReceivedAtUtc = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                ProcessedAtUtc = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true)
            },
            constraints: table =>
            {
                table.PrimaryKey("PK_inbox_messages", x => new { x.Consumer, x.EventId });
            });

        migrationBuilder.CreateIndex(
            name: "ix_inbox_consumer_event_id",
            table: "inbox_messages",
            columns: _inboxColumns,
            unique: true);

        migrationBuilder.CreateIndex(
            name: "ix_inbox_processed_at",
            table: "inbox_messages",
            column: "ProcessedAtUtc");
    }

    /// <inheritdoc />
    protected override void Down(MigrationBuilder migrationBuilder)
    {
        ArgumentNullException.ThrowIfNull(migrationBuilder);

        migrationBuilder.DropTable(
            name: "inbox_messages");
    }
}
