// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Lunara.Infrastructure.Host.Migrations;

/// <inheritdoc />
public partial class AddMessagingTables : Migration
{
    /// <inheritdoc />
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.CreateTable(
            name: "messaging_conversations",
            columns: table => new
            {
                Id = table.Column<Guid>(type: "uuid", nullable: false),
                MatchId = table.Column<Guid>(type: "uuid", nullable: false),
                User1Id = table.Column<Guid>(type: "uuid", nullable: false),
                User2Id = table.Column<Guid>(type: "uuid", nullable: false),
                CreatedAtUtc = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false)
            },
            constraints: table =>
            {
                table.PrimaryKey("PK_messaging_conversations", x => x.Id);
            });

        migrationBuilder.CreateTable(
            name: "messaging_messages",
            columns: table => new
            {
                Id = table.Column<Guid>(type: "uuid", nullable: false),
                ConversationId = table.Column<Guid>(type: "uuid", nullable: false),
                SenderId = table.Column<Guid>(type: "uuid", nullable: false),
                RecipientId = table.Column<Guid>(type: "uuid", nullable: false),
                Text = table.Column<string>(type: "character varying(2000)", maxLength: 2000, nullable: false),
                SentAtUtc = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false)
            },
            constraints: table =>
            {
                table.PrimaryKey("PK_messaging_messages", x => x.Id);
                table.ForeignKey(
                    name: "FK_messaging_messages_messaging_conversations_ConversationId",
                    column: x => x.ConversationId,
                    principalTable: "messaging_conversations",
                    principalColumn: "Id",
                    onDelete: ReferentialAction.Cascade);
            });

        migrationBuilder.CreateIndex(
            name: "ix_messaging_conversations_match_id",
            table: "messaging_conversations",
            column: "MatchId",
            unique: true);

        migrationBuilder.CreateIndex(
            name: "ix_messaging_messages_conversation_id",
            table: "messaging_messages",
            column: "ConversationId");
    }

    /// <inheritdoc />
    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropTable(
            name: "messaging_messages");

        migrationBuilder.DropTable(
            name: "messaging_conversations");
    }
}
