// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Lunara.Infrastructure.Host.Migrations;

/// <inheritdoc />
public partial class AddModerationBlocksReports : Migration
{
    /// <inheritdoc />
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.CreateTable(
            name: "moderation_blocks",
            columns: table => new
            {
                id = table.Column<Guid>(type: "uuid", nullable: false),
                blocker_user_id = table.Column<Guid>(type: "uuid", nullable: false),
                blocked_user_id = table.Column<Guid>(type: "uuid", nullable: false),
                created_at_utc = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
            },
            constraints: table =>
            {
                table.PrimaryKey("PK_moderation_blocks", x => x.id);
            });

        migrationBuilder.CreateTable(
            name: "moderation_reports",
            columns: table => new
            {
                id = table.Column<Guid>(type: "uuid", nullable: false),
                reporter_user_id = table.Column<Guid>(type: "uuid", nullable: false),
                target_user_id = table.Column<Guid>(type: "uuid", nullable: false),
                reason = table.Column<string>(type: "character varying(500)", maxLength: 500, nullable: false),
                details = table.Column<string>(type: "text", nullable: true),
                created_at_utc = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
            },
            constraints: table =>
            {
                table.PrimaryKey("PK_moderation_reports", x => x.id);
            });

        migrationBuilder.CreateIndex(
            name: "ix_moderation_blocks_pair",
            table: "moderation_blocks",
            columns: new[] { "blocker_user_id", "blocked_user_id" },
            unique: true);
    }

    /// <inheritdoc />
    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropTable(name: "moderation_blocks");
        migrationBuilder.DropTable(name: "moderation_reports");
    }
}
