// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Lunara.Infrastructure.Host.Migrations;

/// <inheritdoc />
public partial class AddModerationBlocksReports : Migration
{
    /// <inheritdoc />
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.CreateTable(
            name: "moderation_blocks",
            columns: table => new
            {
                Id = table.Column<Guid>(type: "uuid", nullable: false),
                BlockerUserId = table.Column<Guid>(type: "uuid", nullable: false),
                BlockedUserId = table.Column<Guid>(type: "uuid", nullable: false),
                CreatedAtUtc = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
            },
            constraints: table =>
            {
                table.PrimaryKey("PK_moderation_blocks", x => x.Id);
            });

        migrationBuilder.CreateTable(
            name: "moderation_reports",
            columns: table => new
            {
                Id = table.Column<Guid>(type: "uuid", nullable: false),
                ReporterUserId = table.Column<Guid>(type: "uuid", nullable: false),
                TargetUserId = table.Column<Guid>(type: "uuid", nullable: false),
                Reason = table.Column<string>(type: "character varying(1000)", maxLength: 1000, nullable: false),
                Details = table.Column<string>(type: "character varying(1000)", maxLength: 1000, nullable: true),
                CreatedAtUtc = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
            },
            constraints: table =>
            {
                table.PrimaryKey("PK_moderation_reports", x => x.Id);
            });

        migrationBuilder.CreateIndex(
            name: "ix_moderation_blocks_blocked",
            table: "moderation_blocks",
            column: "BlockedUserId");

        migrationBuilder.CreateIndex(
            name: "ix_moderation_blocks_blocker_blocked",
            table: "moderation_blocks",
            columns: new[] { "BlockerUserId", "BlockedUserId" },
            unique: true);

        migrationBuilder.CreateIndex(
            name: "ix_moderation_reports_target",
            table: "moderation_reports",
            column: "TargetUserId");
    }

    /// <inheritdoc />
    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropTable(name: "moderation_reports");
        migrationBuilder.DropTable(name: "moderation_blocks");
    }
}