// <auto-generated />
using System;
using Lunara.Infrastructure.Host.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lunara.Infrastructure.Host.Migrations;

[DbContext(typeof(LunaraDbContext))]
partial class LunaraDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "9.0.1")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("Lunara.Infrastructure.Host.Persistence.OutboxMessageEntity", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<int>("Attempts")
                    .HasColumnType("integer");

                b.Property<string>("EventType")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)");

                b.Property<string>("LastError")
                    .HasMaxLength(2000)
                    .HasColumnType("character varying(2000)");

                b.Property<DateTimeOffset?>("LockedUntilUtc")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTimeOffset>("OccurredAtUtc")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("PayloadJson")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<int>("Status")
                    .HasColumnType("integer");

                b.HasKey("Id");

                b.HasIndex("LockedUntilUtc")
                    .HasDatabaseName("ix_outbox_locked_until");

                b.HasIndex("Status", "OccurredAtUtc")
                    .HasDatabaseName("ix_outbox_status_occurred");

                b.ToTable("OutboxMessages");
            });
#pragma warning restore 612, 618
    }
}
