<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Lunara.Social.Domain\Lunara.Social.Domain.csproj" />
    <ProjectReference Include="..\..\..\Platform\Lunara.SharedKernel\Lunara.SharedKernel.csproj" />
    <ProjectReference Include="..\..\..\Platform\Lunara.BuildingBlocks\Lunara.BuildingBlocks.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
